# Generated by Django 2.0.9 on 2018-10-08 15:36

from django.db import migrations
from zaptain_rt_app.online_configuration import  RtConfigKeys


def empty_config(apps, schema_editor):
    config = apps.get_model('zaptain_rt_app', 'RtConfig')
    for key in RtConfigKeys:
        config(key=key, value='').save()

class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('zaptain_rt_app', '0001_initial')
    ]

    operations = [
        migrations.RunPython(empty_config)
    ]
