# Generated by Django 3.1.1 on 2020-11-04 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zaptain_rt_app', '0003_admin_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='has_ft_url',
            field=models.BooleanField(default=False),
        ),
    ]
